### ISSUE TITLE
Projection Downloads

### ISSUE THREAD

**Issue by tleonard6** [covidvis/covid19-vis#8]
Hello, do you provide csv downloads for your projections?

**Comment by smacke** [comment]
Hi there,

We do not store the trend lines in our data -- they are computed on-the-fly by Altair. This happens at [chart_spec.py:451](https://github.com/covidvis/covid19-vis/blob/6de2f58a3501f56a7c65c38a38955671955eef10/chartlib/chart_spec.py#L451).
